# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Group', folder: 'documentation', file: 'landingpage.html'}
- {name: 'Research', folder: 'documentation', file: 'research.html'}
- {name: 'Publications', folder: 'documentation', file: 'publications.html'}
- {name: 'Group Members', folder: 'documentation', file: 'members.html'}
- {name: 'Public engagement', folder: 'documentation', file: 'public_engagement.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/clatworthylab'}
- {icon: 'github', link: 'https://github.com/clatworthylab'}
- {icon: 'university', link: 'http://www.med.cam.ac.uk/clatworthy/'}
- {icon: 'dna', link: 'https://www.sanger.ac.uk/group/clatworthy-group/'}
- {icon: 'viruses', link: 'https://www.citiid.cam.ac.uk/menna-clatworthy/'}
- {icon: 'database', link: 'https://www.kidneycellatlas.org/'}
- {icon: 'heartbeat', link: 'https://www.cardiovascular.cam.ac.uk/directory/menna-clatworthy'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
# pagination:
  # next_page: 'Newer'
  # previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
